name: Update Changelog

on:
  pull_request:
    # branches to consider in the event; optional, defaults to all
    branches:
      - master

jobs:
  update_changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set Environment
        run: |
          echo ::set-env name=REPOSITORY_USER::$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $1}')
          echo ::set-env name=REPOSITORY_NAME::$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}')
        shell: bash

#      - name: Set up Ruby 2.6
#        uses: actions/setup-ruby@v1
#        with:
#          ruby-version: '2.6'
#      - name: Cache Bundle Directory
#        uses: actions/cache@v2
#        with:
#          path: vendor/bundle
#          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
#      - name: Prepare Bundler
#        run: |
#          gem install bundler
#          bundle config path vendor/bundle
#          bundle install --jobs 4 --retry 3
#      - name: Generate Changelog
#        id: generate_changelog
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        run: |
#          bundle exec github_changelog_generator -u $REPOSITORY_USER -p $REPOSITORY_NAME --token $GITHUB_TOKEN
#          if [[ -e 'CHANGELOG.md' ]]; then
#            export CHANGELOG="$(cat CHANGELOG.md | sed ':a;N;$!ba;s/%/%25/g' | sed ':a;N;$!ba;s/\n/%0A/g' | sed ':a;N;$!ba;s/\r/%0D/g')"
#          fi
#          echo "$CHANGELOG"
#          echo ::set-output name=changelog::"${CHANGELOG}"
#        shell: bash
      - name: Action Generate Changelog
        id: action-github-changelog-generato
        uses: heinrichreimer/action-github-changelog-generator@v2.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Display Changelog
        run: |
          echo "GITHUB_REF->$GITHUB_REF"
          echo ${{ steps.action-github-changelog-generato.outputs.changelog }}
          ls -la
          cat CHANGELOG.md
        shell: bash
#      - name: Commit files
#        env:
#          AUTHOR_NAME: 'Add & Commit Action'
#          AUTHOR_EMAIL: 'actions@github.com'
#        run: |
#          git config --local user.email "$AUTHOR_EMAIL"
#          git config --local user.name "$AUTHOR_NAME"
#
#          git add CHANGELOG.md
#          git commit -m "Update Changelog" --author="$AUTHOR_NAME <$I$AUTHOR_EMAIL>"
#
#          git add CHANGELOG.md && git commit -m 'Updated CHANGELOG.md' && echo ::set-env name=push
#
#          git push --set-upstream origin
      - name: Add & Commit
        uses: EndBug/add-and-commit@v4.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          ref: 'changelog'
          message: 'Update Changelog'
          add: ./CHANGELOG.md
#      - name: pr-changelog
#        uses: Guzzler/file-changelog-issue-action@1.0.1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
