name: Update Changelog

on:
  pull_request:
    # branches to consider in the event; optional, defaults to all
    branches:
      - master

jobs:
  generate:
    name: Generate Changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Action Generate Changelog
        uses: heinrichreimer/action-github-changelog-generator@v2.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Changelog
        uses: actions/upload-artifact@v2
        with:
          name: changelog
          path: CHANGELOG.md

  create-pull-request:
    name: Create Pull Request
    runs-on: ubuntu-latest
    needs: generate
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: master
          fetch-depth: 0
      - name: Download Changelog
        uses: actions/download-artifact@v2
        with:
          name: changelog
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          branch: changelog
          title: 'Update Changelog'
          body: |
            Update Changelog
            - Auto generated with PR:#${{ github.event.pull_request.number }}
          reviewers: |
            granoeste
