on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  createrelease:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set Environment
        run: |
          echo ::set-env name=REPOSITORY_USER::$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $1}')
          echo ::set-env name=REPOSITORY_NAME::$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}')
        shell: bash
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - name: Install github_changelog_generator
        run: |
          gem install github_changelog_generator
      - name: Generate CHANGELOG
        run: |
          github_changelog_generator -u $REPOSITORY_USER -p $REPOSITORY_NAME -t ${{ secrets.GITHUB_TOKEN }}
#      - name: changelog
#        id: changelog
#        uses: heinrichreimer/github-changelog-generator-action@v2.1.1
#        with:
#          token: ${{ secrets.GITHUB_TOKEN }}
#      - name: Conventional Changelog Action
#        id: changelog
#        uses: TriPSs/conventional-changelog-action@v3
#        with:
#          github-token: ${{ secrets.github_token }}
##          git-user-name: 'granoeste'
##          git-user-email: 'granoeste@gmail.com'
#          preset: eslint
#          output-file: 'false'
##          release-count: 0
##          skip-on-empty: 'true'
#          skip-commit: 'true'
#          skip-version-file: 'true'
#
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
#          body: |
#            ${{ steps.changelog.outputs.changelog }}
          body_path: ${GITHUB_WORKSPACE}/CHANGELOG.md
#          tag_name: ${{ steps.changelog.outputs.tag }}
#          release_name: ${{ steps.changelog.outputs.tag }}
#          body: ${{ steps.changelog.outputs.clean_changelog }}
          draft: false
          prerelease: false
